name = "emobanana"
main = "backend/build/worker/shim.mjs"
compatibility_date = "2024-01-01"

# KV namespace for rate limiting
kv_namespaces = [
  { binding = "RATE_LIMIT_KV", id = "94dfacdd3b824ec293281a8019f4c15c", preview_id = "94dfacdd3b824ec293281a8019f4c15c" }
]

[build]
command = "cd backend && cargo install -q worker-build && ~/.cargo/bin/worker-build --release --no-opt"

# GEMINI_API_KEY is loaded from .dev.vars for local dev
# For production, set as secret: wrangler secret put GEMINI_API_KEY